### ISSUE TITLE
PerturbationAnalysis - algorithm is wrong

### ISSUE THREAD

**Issue by albermax** [albermax/innvestigate#102]
It seems as the perturbation analysis code does not implement the cited algorithm from:

*[Samek et al.](http://dx.doi.org/10.1109/TNNLS.2016.2599820)*, "Evaluating the visualization of what a deep neural network has learned." *IEEE transactions on neural networks and learning systems* 28.11 (2017): 2660-2673.

The region to perturb should be selected of the ordering of the analysis for the input image, not after each perturbation.

**Comment by heytitle** [comment]
Hi Max,

I can take a look into this issue. 

Cheers,
Pat

**Comment by albermax** [comment]
Hi Pat,

sorry, it is a bit intransparent. I was already in touch with Philipp who wrote the original code and he will fix it.
If you don't mind I would be better if you look into additional algorithms to implement.

Cheers,
Max

**Comment by pseegerer** [comment]
#107 should solve this.
