### ISSUE TITLE
Error while running the library tests

### ISSUE THREAD

**Issue by champnaman** [albermax/innvestigate#103]
So I have been trying to use the repository for my project. After setting up the environment exactly as mentioned in in the Readme, I get an error while running the tests (can be seen in the attached image). 

Could you please tell me why is this happening? Or there is no error and everything is working perfectly. It would be of great help if you help me out. 

(I would just like to mention that I did not try to run anything after step since I am assuming it is some sort of error).

Thanks, 
NamanB

![screenshot from 2018-10-04 20_28_53](https://user-images.githubusercontent.com/5251592/46511732-e19f9300-c815-11e8-98fa-bc00a1c46f66.png)

**Comment by albermax** [comment]
Hi Naman,

I think this happening because you did not configure the right Keras backend.
Did you install and select a backend? (See here in case: https://keras.io/backend/)
E.g., you can set it also like that if you have Tensorflow installed:

```bash
KERAS_BACKEND=tensorflow python setup.py test
```

Does this fix your issue?

Cheers,
Max

**Comment by champnaman** [comment]
Hi Albert, 

Thanks for responding. 

Also, sorry, I could not see your response during this weekend. 
(I would also like to mention that I am just starting out using Keras. I have some experience with Tensorflow but not with Keras. I hope you would understand and be kind enough to guide me).

I did exactly what you suggested, but I am still getting the same error.
![query](https://user-images.githubusercontent.com/5251592/46618939-64f70800-cae6-11e8-90ef-240945468583.png)
 
Based on the documentation, I tried to check the keras.json file to see if it takes Tensorflow as its backend and everything seems to be right there.
![query2](https://user-images.githubusercontent.com/5251592/46618974-7809d800-cae6-11e8-8f2f-6721a7c6cef3.png)

I am also attaching the following image to make sure that I have installed the correct version of python and Tensorlfow as mentioned. 
![qu](https://user-images.githubusercontent.com/5251592/46619050-ba331980-cae6-11e8-9cab-dce000d0fafe.png)

Please let me know how I can solve this issue. 

Thanks, 
NamanB

**Comment by champnaman** [comment]
Hey Albert, 

Thanks for the response. I still get the same error while running the tests. 

But I was trying to run the example notebooks and it seems to be working fine. 

I shall let you know in case I face some other issue/error. 

There is one more thing that I would like to mention. As mentioned in the setup.py, one of the requirements is Keras version 2.2.2 with the tensorflow backend. But it doesn't work with the latest version of the tensorflow (1.11.0). In my usage, it works with tensorflow 1.8.0. (I was having problems setting it up while using virtualenv/virtualenvwrapper because of the version issues. Anaconda helped me find the compatible versions).

Thanks for your help. 

Naman

**Comment by albermax** [comment]
Hi Naman,

that's good to hear! and please let us know if you run into troubles!

Hmm, could you specify why it did not work with TF 1.11?
We did not test it with that version, but it would be good to know what the exact issue is.

Cheers,
Max

**Comment by champnaman** [comment]
Hi Albert, 

This error is pretty weird and I do not know why is it even happening. 

As you mentioned, I can install this library via two methods i.e. 
1. pip install git+https://github.com/albermax/innvestigate (tried in venv_tf1)
2. python setup.py install (tried in venv_tf)

If I install using the second method, I do not get any error message but if I install using the first method, I get the following error
_keras 2.2.2 has requirement keras-applications==1.0.4, but you'll have keras-applications 1.0.6 which is incompatible.
keras 2.2.2 has requirement keras-preprocessing==1.0.2, but you'll have keras-preprocessing 1.0.5 which is incompatible._

This can be seen in the following image as well.
![git](https://user-images.githubusercontent.com/5251592/47112526-3d0d5000-d21c-11e8-9336-cfdfba89ee7e.png)


But the most weird thing is that the versions of the packages (keras-applications, keras-preprocessing) installed in both the environments are the same. 
![direct](https://user-images.githubusercontent.com/5251592/47112387-cb350680-d21b-11e8-854b-ee692eeb6fdb.png)
![venv_tf1](https://user-images.githubusercontent.com/5251592/47112424-e43db780-d21b-11e8-82a4-be4771babd9a.png)

Thanks, 
Naman

**Comment by albermax** [comment]
Hi Naman,

thanks again for posting! This is indeed strange. Not sure what is happening here, but it seems like a Python problem.

I will close the issue now, if you find any strange behaviour of the library, please let us know!

Btw my surname is Alber, w/o the t :-)
Cheers,
Max
