### ISSUE TITLE
Support bare Tensorflow-models?

### ISSUE THREAD

**Issue by WGierke** [albermax/innvestigate#106]
This library is extremely helpful when it comes to understanding what a model learned, thank you guys!
I was wondering whether it would be possible to support Tensorflow-models as well?
Currently, it seems like one is supposed to wrap that model somehow into keras, such that iNNvestigate can then manipulate the underlying Tensorflow-methods again.
Do you see any nice way to support Tensorflow-models without wrapping them in keras first?

**Comment by albermax** [comment]
Hi Willi,

I'm afraid there will be no support for bare Tensorflow models and I also don't see any nice way (except for a automatic model conversion, see below). IMHO it is not feasible to parse bare TF graphs, e.g., there are so many ways to code a ReLU etc. Therefore we stick to Keras and rely on it's conventions.

Though what you can do is to train with TF and port the weights to a Keras model.
Maybe this helps: https://github.com/ysh329/deep-learning-model-convertor

Good luck! and it would be great if you could let us know if you found a good way!

Cheers,
Max
