### ISSUE TITLE
Segmentation Fault running setup.py test

### ISSUE THREAD

**Issue by alsmeirelles** [albermax/innvestigate#119]
Hello,

I recently installed innvestigate as a user module (pip install --user...). When running the test script I get:

running pytest
running egg_info
writing innvestigate.egg-info/PKG-INFO
writing dependency_links to innvestigate.egg-info/dependency_links.txt
writing requirements to innvestigate.egg-info/requires.txt
writing top-level names to innvestigate.egg-info/top_level.txt
reading manifest file 'innvestigate.egg-info/SOURCES.txt'
writing manifest file 'innvestigate.egg-info/SOURCES.txt'
running build_ext
=============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.6.6, pytest-3.9.3, py-1.7.0, pluggy-0.8.0
rootdir: /Path/To/Lib/innvestigate, inifile: setup.cfg
collected 104 items / 9 deselected                                                                                                                                                

innvestigate/tests/analyzer/test_base.py Segmentation fault: 11

If I import innvestigate from the python terminal it is loaded with no errors. I will try to test it in other ways but for now, the default testing script causes some strange segfault.

I'll be happy to provide any further information needed.

I'm running on a MacOS 10.13.6
Keras version is 2.2.2
Tensorflow 1.8.0
Python 3.6.6

**Comment by albermax** [comment]
Hi André,

thank you for posting. This seems related to issue #103 
Unfortunately I am not sure right now what the issue is. I will look into issue again once I have time!
If you note anything strange while using the library please let us know!

Cheers,
Max

**Comment by ghwatson** [comment]
Same issue running the tests.
Ubuntu 16.04
Tensorflow 1.8.0
Python 3.6.6

Happy to also help!

**Comment by albermax** [comment]
Hi guys,

I was able to reproduce the bug. The issue seems to be Tensorflow version 1.8.0, when updating to 1.12.0 the tests passed. Our bad for not updating the readme, sorry.

Can you update Tensorflow? If not I can dig deeper and see what I can do.

Cheers,
Max

**Comment by albermax** [comment]
I meant Tensorflow 1.10.1 (that's the version I currently use), but I think with a newer setup the code should work too!

Cheers,
Max

**Comment by alsmeirelles** [comment]
Hi Max,

Thanks for your quick response! I'll try it tonight and report back latter.

Cheers!
