### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ghazalmazaheri** [albermax/innvestigate#124]
When I try to use   
gradient_analyzer = innvestigate.analyzer.Gradient(model)
analysis = gradient_analyzer.analyze(Image)
I got following error:

Using TensorFlow backend.
Traceback (most recent call last):
  File "CNN-keras6.py", line 15, in <module>
    import innvestigate
  File "/home/gmaza002/vcg/lrp/innvestigate/__init__.py", line 2, in <module>
    from . import analyzer
  File "/home/gmaza002/vcg/lrp/innvestigate/analyzer/__init__.py", line 18, in <module>
    from .base import *
  File "/home/gmaza002/vcg/lrp/innvestigate/analyzer/base.py", line 25, in <module>
    from .. import layers as ilayers
  File "/home/gmaza002/vcg/lrp/innvestigate/layers.py", line 653
    def __init__(self, *args, regularizer=None, constraint=None, **kwargs):
                                        ^
SyntaxError: invalid syntax

**Comment by albermax** [comment]
Hi ghazalmazaheri,

do use Python 2?
Unfortunately, we dropped Python 2 support at some point.
It's merely some syntax problems. If you really need it please let me know and I can have look!

Cheers,
Max

**Comment by ghazalmazaheri** [comment]
Hi Max, 

Thank you so much for your reply.
Yes, I use python 2. I really appreciate it if you could kindly look at it. I would like to use it with python 2.

Regards,
Ghazal

**Comment by clennan** [comment]
It seems in Python 2 you must put default arguments before `*args`
https://stackoverflow.com/a/15302042/10306233

**Comment by albermax** [comment]
Hi ghazalmazaheri & Christopher,

thanks! I will look into it.

Cheers,
Max

**Comment by albermax** [comment]
I fixed several issues, now the code should run with Python 2 again too!

Cheers,
Max
