### ISSUE TITLE
Wrong command in README

### ISSUE THREAD

**Issue by TimoK93** [albermax/innvestigate#128]
Hey guys,
nice work at all!

I noticed, that this command from your README does not work.

`python setup.py test -m precommit`

The error that is raised is 

```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option -m not recognized
```

If i delete the -m argument the same message with "precommit" is raised!

I "fixed" it using 
`python setup.py test`

- Ubuntu 16.04
- Python 3.5.2

Thanks,
Timo

**Comment by albermax** [comment]
You are right :-)
I fixed it in the dev branch.

Thank you!
Cheers,
Max
