### ISSUE TITLE
The execution of this package is very slow

### ISSUE THREAD

**Issue by Tahedi1** [albermax/innvestigate#129]
Is there any batch version for this package. Can I use the analyser for a batch of images ?

**Comment by Tahedi1** [comment]
Hi Albert,

Thanks for giving me the information about the use of batch.
I'm using GeForce GTX 1080 Ti GPU. The analysis of one image (batch) take more than 2 second.

Kind regards

**Comment by albermax** [comment]
At the first analysis the graph is compiled. Every further analysis should be faster.

Cheers,
Max

**Comment by Tahedi1** [comment]
Thanks albermax.

**Comment by albermax** [comment]
Let us know if you have any further troubles!
