### ISSUE TITLE
Tuple object has no attribute pop

### ISSUE THREAD

**Issue by jmaces** [albermax/innvestigate#133]
When setting a specific neuron in neuron selection mode `"index"` for **smoothgrad** analyzer I get the error message 

`tuple object has no attribute pop`.

I guess somewhere `*args` is not passed on as expected. The error comes from [wrapper.py](https://github.com/albermax/innvestigate/blob/master/innvestigate/analyzer/wrapper.py) but I did not track back where the tuple actually comes from. A simple quickfix would be casting to list at the problematic line.

**Comment by albermax** [comment]
Thank you also for this fix!!

Cheers,
Max
