### ISSUE TITLE
Is there a way to obtain the relevance per node using LRP

### ISSUE THREAD

**Issue by Next-RicardoGuerrero** [albermax/innvestigate#135]
Hi,

I would like to examine a network in depth, checking the relevance distribution per layer. Is there a way to obtain this? For instance: the relevance on layer 2, neuron 0.

Thanks

**Comment by albermax** [comment]
Hi Ricardo,

yes, you build a model with 2 layers and use the neuron indexing mode to select neuron 0.
Does this help you?

Cheers,
Max

**Comment by Next-RicardoGuerrero** [comment]
Hello,

in that case is a solution, but it restricted me to very simple architectures. I would like use models with 4 layers, 5, dropout, etc.

Is it possible with this library?

**Comment by albermax** [comment]
Hi Ricardo,

why should this not work?
You anyway need to build the model; only that in this case you would stop building it once you arrived at the layer you want to analyze.
How would you do it otherwise?

Cheers,
Max

**Comment by jurgyy** [comment]
@Next-RicardoGuerrero Not sure if I understand your problem correctly, but just build your (deep) model as you normally would. Then remove the last `n` layers like this:

    def cut_last_layer(model, n=1):
        return Model(inputs=model.inputs, outputs=model.layers[-1-n].output)

So the last layer of the cut model is the one you want to analyze. Then create an analyzer with the cut model with `neuron_selection_mode="index"` like this:

    analyzer = innvestigate.create_analyzer("lrp.alpha_1_beta_0", cut_last_layer(model, n=3), neuron_selection_mode="index")

and then analyze the a specific node:

    analyzer.analyze(x, node)
