### ISSUE TITLE
Error when running on InceptionV3

### ISSUE THREAD

**Issue by dokato** [albermax/innvestigate#136]
Hi, thanks for the module. It's really great :) 

I have a problem though. I tried to run it on `InceptionV3` model from keras and I'm getting an error with some methods: `smoothgrad` and `deeplift` (both versions). `deep_taylor` and `lrp` seem to be working okay.

```python
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import innvestigate
import innvestigate.utils as iutils
import innvestigate.utils.visualizations as ivis

import keras

from keras.preprocessing import image
from keras.applications import inception_v3
from keras import backend as K
from PIL import Image

img = image.load_img('cat.jpg', target_size=(299, 299))
img = image.img_to_array(img)
img /= 255.
img -= 0.5
img *= 2.
img = np.expand_dims(img, axis=0)

model = inception_v3.InceptionV3()

model_wo_softmax = iutils.keras.graph.model_wo_softmax(model)
analyzer_sg = innvestigate.create_analyzer("smoothgrad", model_wo_softmax)
analyzer_dl = innvestigate.create_analyzer("deep_lift", model_wo_softmax)

ana_sg = analyzer_sg.analyze(img)
```

Confusingly, the error messege is also different. So here for `smoothgrad`:
```
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (-1, 64, None, None, 3). Consider casting elements to a supported type.
```

and here for `deeplift`:

```
> ana_dl = analyzer_dl.analyze(img)

ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_1_1/convolution' (op: 'Conv2D') with input shapes: [1,1,1,3], [3,3,3,32].
```

I tested on couple of images, but can send you the one particular if that helps. 

I'm using python `3.5.6`.

**Comment by albermax** [comment]
Hi Dokato,

you are welcome :-)

The issue with smoothgrad is that the implementation requires exact knowledge about the shape.
It's not ideal, but here is a workaround:
```python
model = inception_v3.InceptionV3(input_shape=(299, 299, 3))
```

I removed our deeplift implementation for now. It seems to be buggy, thus I ask you to use the original one via "deeplift.wrapper".
Unfortunately, it seems that original implementation does not work with InceptinV3, at least I got an error.
Or our wrapper has a bug; in that case please let us know!

Cheers,
Max

**Comment by dokato** [comment]
Thank you, @albermax for a prompt reply. I'll test deeplift wrapper more and see where the problem occurs.

**Comment by albermax** [comment]
Great!
