### ISSUE TITLE
Issue/Query Regarding the Visualization Techniques in the library

### ISSUE THREAD

**Issue by champnaman** [albermax/innvestigate#139]
I have few queries regarding the visualization techniques given in the `innvestigate\utils\visualizations.py` file. 

For example, `gradient` method applies `imagenetutils.graymap` postprocessing function which is equivalent to applying `heatmap` function from the `visualization.py` with `cmap_type="gray"` as the input paramter. So for the gradient analysis of a colored image (let's say `227*227*3`), what it does is as following as per my understanding -

1. Sum across the color channel (you get `227*227`)
2. Linearly project this `227*227` matrix in the range of `(0, 255)`
3. Flattens it and applies the colormap (`cmap(tmp.flatten())`), which results in a new matrix of `((227*227)*4)` (Not sure how it becomes _4_, may be something from matplotlib)
4. This command (`tmp = cmap(tmp.flatten())[:, :3].T`) selects only the first three channels from the previous part, i.e. the resulting shape is `(3*(227*227))`  (with a max of 1 and min of 0)

I mean if we are bringing it to the range of (0, 1), why not directly rescale it this range and visualize it using matplotlib with gray color map. Will it be any different from the procedure that you are doing?

Similarily, when you apply `imgnetutils.heatmap` for _lrp_ methods, you are first applying gamma correction on it (I guess, to get better contrat of the visualization). But does it not change the actual analysis results (**which would mean that the heatmap does not correspond to the model explanation as given by a particular method**) or is it just for the good looking visualization results.

It would be of huge help to me if you could please elaorate on some of these queries/ thought process behind these visualization techniques/ best practices. Or is it something a standard procedure that I followed in the community which I am aware of. 

Thanks, 
Naman

**Comment by albermax** [comment]
Hi Naman,

this is one way to apply the colormap. I'm sure there are other ones that work as well.

The gamma correction should not be there and should be removed in the develop branch.

To the points:
3. The 4. channel is alpha (transparency).
4. Here the colormap is applied.

Does this help you?

Cheers,
Max

**Comment by jurgyy** [comment]
> The 4. channel is alpha (transparency).

The heatmap function doesn't support an alpha channel though. Here's my adaptation of the method from when I wanted to overlay my custom cmap function on top of an image:

```python
def register_cm_seismic_alpha():
    cm = plt.cm.get_cmap("seismic")
    a = np.linspace(0, 1, cm.N)
    m = np.array(list(map(cm, a)))
    m[:, 3] = 1 - (m[:, 0] + m[:, 1] + m[:, 2]) / 3
    my_cm = LinearSegmentedColormap.from_list("seismic_alpha", m, N=cm.N)
    plt.register_cmap(cmap=my_cm)


register_cm_seismic_alpha()


def heatmap_gamma(X, cmap_type="seismic"):
    X = ivis.gamma(X, minamp=0, gamma=0.95)
    return heatmap(X, cmap_type=cmap_type, alpha_cmap=True)


def heatmap(X, cmap_type="seismic", reduce_op="sum", reduce_axis=-1, alpha_cmap=False, **kwargs):
    cmap = plt.cm.get_cmap(cmap_type)

    tmp = X
    shape = tmp.shape

    if reduce_op == "sum":
        tmp = tmp.sum(axis=reduce_axis)
    elif reduce_op == "absmax":
        pos_max = tmp.max(axis=reduce_axis)
        neg_max = (-tmp).max(axis=reduce_axis)
        abs_neg_max = -neg_max
        tmp = np.select([pos_max >= abs_neg_max, pos_max < abs_neg_max],
                        [pos_max, neg_max])
    else:
        raise NotImplementedError()

    tmp = ivis.project(tmp, output_range=(0, 255), **kwargs).astype(np.int64)

    if alpha_cmap:
        tmp = cmap(tmp.flatten()).T
    else:
        tmp = cmap(tmp.flatten())[:, :3].T
    tmp = tmp.T

    shape = list(shape)
    shape[reduce_axis] = 3 + alpha_cmap
    return tmp.reshape(shape).astype(np.float32)
```

**Comment by jurgyy** [comment]
[Done](https://github.com/albermax/innvestigate/pull/140)
