### ISSUE TITLE
LRP with models with Lambda layers

### ISSUE THREAD

**Issue by gchlebus** [albermax/innvestigate#141]
The `AnalyzerNetworkBase ` default parametrization is to disable support for Lambda layers. I would like to analyze a u-net model which uses Lambda layers to perform cropping when concatenating feature maps (it is needed when working with dynamic shapes). My implementation is below:
```python
def center_crop(tensor, target_shape):
  input_shape = K.shape(tensor)
  crop = K.cast((input_shape - target_shape) // 2, "int32")
  return Lambda(lambda y: y[:, :, crop[2]:-crop[2], crop[3]:-crop[3], crop[4]:-crop[4]])(tensor)
```
My question would be whether my LRP analysis of this model would be correct if I set `allow_lambda_layers=True` when creating the analyzer.

**Comment by albermax** [comment]
Hi Grzegorz,

yes, that's fine. Then the relevance will be attributed correctly.

Dheers,
Max

**Comment by gchlebus** [comment]
Thanks!
