### ISSUE TITLE
Model with more than one output

### ISSUE THREAD

**Issue by beatriz-ferreira** [albermax/innvestigate#146]
Hi,

I was trying to run innvestigate for a custom model that has more than one output (kind of a multi-task model). I am also getting the following error (already mentioned in):
line 370-371 of `analyzer/base.py`

```python
        if len(model_output) > 1:
            raise ValueError("Only models with one output tensor are allowed.")
```

So I guess I have to split it into two different models

_Originally posted by @jurgyy in https://github.com/albermax/innvestigate/issues/137#issuecomment-470149510_

Is there any way of analyzing such a model with more than one output? I'm really interested in keeping the two outputs, i.e. a joint model, as the two outputs predict different level classifications (categories and attributes) of the same image. Since these two outputs are related I would like to study them together. 
Is there any way of applying innvestigate for such a case?

Thank you!

**Comment by albermax** [comment]
Hi Beatriz,

how about adding a concatenation layer in the end?
Sorry, it's a bit inconvenient.
We will keep it in mind for the major, upcoming update.

Cheers,
Max

**Comment by beatriz-ferreira** [comment]
Hi Max,

Thank you for your reply. 
I'll try that! Adding a concatenation layer shouldn't change any behaviour of the interpretation, is that correct?

Yes, it would be great if the major upcoming update considered this issue!!

Best,
Beatriz

**Comment by albermax** [comment]
No, mind that most/all analysis methods work w.r.t. to one output neuron.
Thus it only changes the way you index them.

We will!

Cheers

**Comment by ujjwalnur** [comment]
@albermax  Has this been worked on ?
