### ISSUE TITLE
Get relevance score per layer

### ISSUE THREAD

**Issue by mbenhamd** [albermax/innvestigate#151]
Hi, let's say I have a simple MLP with 6 layers : 
First layer : 2539 neurones
Second layer : 4564 neurones
Third layer : 4519 neurones
Fourth layer : 2141 neurones 
Fifth layer : 383 neurones
Last layer : 2 neurones
How can i get the relevance score for each layer in this format :  (x_exemple_length,nb_neurones) ?

**Comment by SimonMeyerLauritsen** [comment]
Use the parameter "reverse_keep_tensors=True" when calling "create_analyzer". Then all layers are stores in the analyser.

**Comment by mbenhamd** [comment]
`analyzer = innvestigate.create_analyzer("gradient",model,reverse_keep_tensors=True)
analysis = analyzer.analyze(x_valid)
analysis.shape # Shapie is(5578, 54675), 5578 lines of x_valied and 54675 is my number of input variables`
How do i get relevance score for other layers ?

**Comment by albermax** [comment]
Yes, Simon is right. This is at the moment the easiest way.

**Comment by albermax** [comment]
Thanks Simon!
