### ISSUE TITLE
Issue in using iNNvestigate for 3DCNN classifiers?

### ISSUE THREAD

**Issue by janzaib-masood** [albermax/innvestigate#153]
Hi AlberMax,

I have problems using the heatmap methods in iNNvestigate for neuroimaging models/data. So can you please let me know, for now which methods in iNNvestigate support 3DCNN architectures?

**Comment by derEitel** [comment]
Which methods do you have issues with?
I am not related to the innvestigate developers but have recently used it successfully in neuroimaging. Check out the repo:
https://github.com/derEitel/explainableMS

And specifically:
https://github.com/derEitel/explainableMS/blob/master/INNvestigate-normal%20MS%20FLAIR.ipynb

**Comment by albermax** [comment]
Hi, all methods except PatternAttribution and PatternNet should work!
If you have issues it would be great, if you would post a stacktrace/minimal example.
Thanks!
