### ISSUE TITLE
Save Analyzer Model for Subsequent LRP Estimates

### ISSUE THREAD

**Issue by dmracek** [albermax/innvestigate#155]
Hello,

I really enjoy this repo thank you for putting it together. I'm running into a problem when I want to save the analyzer model for future use. Is there a reproducible example that uses save_npz(). The documentation provided is pretty straightforward on the website is but I'm running into an error. Do I need to save() and pass to save_npz()?

@albermax do you have an example or anyone out there have an example they'd be willing to share?

https://innvestigate.readthedocs.io/en/latest/modules/analyzer.html

**Comment by enryH** [comment]
sound correct looking at: [save_npz](https://innvestigate.readthedocs.io/en/latest/modules/analyzer.html#innvestigate.analyzer.base.AnalyzerBase.save_npz)

Does the LRP method need training or why do you want to save the analyzer?

**Comment by dmracek** [comment]
I'd like to save the analyzer so I could make predictions for future use like in a web application similar to the heatmapping.org demo.

**Comment by enryH** [comment]
Maybe I am not getting it, but I think that what you need to save to reproduce the decomposition is the keras model, e.g. as json, and the model-weights. From there you can load your model and then "use" the analyzer. In a web application this would then be somehow integrated to a Flask Server?!
