### ISSUE TITLE
How to define LRP rule?

### ISSUE THREAD

**Issue by iBM88** [albermax/innvestigate#172]
I tried to use LRP as iNNvestigate's analyzer but in the error it said that i need to define rules. Where can I find an example of that?
I realized that rules should be defined in `create_analyzer(name, model, **kwargs)` in kwargs but I get the error:

> TypeError: create_analyzer() takes 2 positional arguments but 3 were given

**Comment by NilsHeil** [comment]
How did you solve it?

**Comment by iBM88** [comment]
> How did you solve it?

implemented LRP myself.

**Comment by enryH** [comment]
Which rule were you missing?

**Comment by MN5930** [comment]
Have you guys implemented the CMP rule yet? Would you please let me know? thanks.
