### ISSUE TITLE
Analysing custom layers and regression networks

### ISSUE THREAD

**Issue by vandana-rajan** [albermax/innvestigate#174]
Hi,

First of all, thanks for this wonderful toolkit. 
I would like to know how I can use this framework when analysing networks that contain

(1) custom layers like an attention layer.

(2) regression output instead of softmax classification.

Thanks,
VR

**Comment by Ahgni** [comment]
> Hi,
> 
> First of all, thanks for this wonderful toolkit.
> I would like to know how I can use this framework when analysing networks that contain
> 
> (1) custom layers like an attention layer.
> 
> (2) regression output instead of softmax classification.
> 
> Thanks,
> VR

I also changed softmax with the regression layer. And it works for me if I remove this sentense
`   model = innvestigate.utils.model_wo_softmax(model)#Creates a new model w/o the final softmax activation.
`
Hope it works for you too.

**Comment by adrhill** [comment]
Hi @vandana-rajan,

iNNvestigate focuses on classifiers, but there are ways to apply LRP to regression models. 
Check out the [XAI for regression](https://xai-regression.org) webpage as well as [Letzgus et al., "Toward Explainable AI for Regression Models"](https://arxiv.org/abs/2112.11407).
