### ISSUE TITLE
does this library support tensorflow model rathe than keras model?

### ISSUE THREAD

**Issue by miss1997yuan** [albermax/innvestigate#175]
excuse me .would someone give me some suggestion if the library supports the tensorflow model

**Comment by BraveDistribution** [comment]
No, it doesn't. tf.keras is not supported.

**Comment by adrhill** [comment]
Hi @miss1997yuan,

we just released [iNNvestigate 2.0](https://github.com/albermax/innvestigate/releases/tag/2.0.0) with support for TensorFlow 2 and `tf.keras` models! 
Please try it out and let me know if this fixes your issue. :)
