### ISSUE TITLE
KeyError: '--' when trying to recreate imagenet_compare_networks.ipynb

### ISSUE THREAD

**Issue by NilsHeil** [albermax/innvestigate#183]
When I start running the analyses, I get the output "Creating analyses for network vgg16", but then comes the KeyError '--' for line 24: text.append(("%s" % label_to_class_name[y],

**Comment by enryH** [comment]
Do you use TF1 or the TF2?

**Comment by NilsHeil** [comment]
1.15.0

**Comment by enryH** [comment]
It says it's tested with 1.12, but it might also work with 1.13 or 1.14. (I set up a test later to see what works)

**Comment by enryH** [comment]
The example worked with TF1.14. Did you get it to run?

**Comment by enryH** [comment]
Your are right, I did not see that you are referring to [imagenet_compare_networks.ipynb](https://github.com/albermax/innvestigate/blob/master/examples/notebooks/imagenet_compare_networks.ipynb).

So the key `--` is assigned by a function called [`get_class`](https://github.com/albermax/innvestigate/blob/1ed38a377262236981090bb0989d2e1a6892a0b1/examples/utils.py#L47) which should load the images, and is supposed to indicate picking a random image, but here we need a specific one. 

On the way I found that other examples are also not running... I myself never run all examples, so it could be a nice exercise.
