### ISSUE TITLE
Question to the analysis array

### ISSUE THREAD

**Issue by NilsHeil** [albermax/innvestigate#185]
`analyzer = innvestigate.create_analyzer("deep_taylor",
                                        model,
					neuron_selection_mode="index")
analysis = analyzer.analyze(inputs, i)`

Do the values of the analysis array refer to the activation of the NN? So, if a value in the array is high, then it means that the pixel this value refers to triggers the output of the NN in a positive manner?

**Comment by enryH** [comment]
yes, but there are several variants. The final layer (without sigmoid/softmax) is decomposed to the original inputs.
