### ISSUE TITLE
[Documentation request] Equations of LRP rules

### ISSUE THREAD

**Issue by pmartineauGit** [albermax/innvestigate#224]
Dear @albermax,

First, thank you very much for the amazing module!

I am using LRP analysis with a simple multilayer perceptron-based
classifier but I am unsure about what is going on in the analysis since
I was not able to find the mathematical expressions for the predefined
rules.

I had a look at https://innvestigate.readthedocs.io/en/latest/modules/analyzer.html,
"iNNvestigate Neural Networks!", and "Software and application patterns for explanation methods",
but I could not find any description of the rules listed in innvestigate/innvestigate/analyzer/relevance_based/relevance_rule.py 

Could you please point me to some reference describing the LRP rules?

Thank you very much,
Best,
Patrick

**Comment by rachtibat** [comment]
Hi,
you could have a look at https://arxiv.org/pdf/1910.09840.pdf
and also at http://www.heatmapping.org/tutorial/

For the code you have to look at
relevance_rule_base.py you find it in analyser/relevance_based

Best
