### ISSUE TITLE
Problem with neuron Selection mode

### ISSUE THREAD

**Issue by mariokloster** [albermax/innvestigate#232]
Hello,

Thank you for this great Tool.
I have a Problem with neuron_selesction_mode in version updates_towards_tf2.0 
```Python
my_analyzer = create_analyzer("lrp.sequential_preset_a", model_wo_sm, neuron_selection_mode="index")
```

/innvestigate/analyzer/base.py in __init__(self, model, allow_lambda_layers, **kwargs)
    258 
    259 
--> 260         super(AnalyzerNetworkBase, self).__init__(model, **kwargs)
    261 
    262     def _add_model_softmax_check(self):

TypeError: __init__() got an unexpected keyword argument 'neuron_selection_mode'

**Comment by rachtibat** [comment]
Hi,
I'm sorry version 2.0 is right now not usable. If you want something reliable to play with use comment 4f558f8ccd4b6762d5386700777cbb0641d9834f

neuron_selection_mode is no argument anymore. Just open the function and look at the comments. They should explain how you use the function. There is unfortuantely no documentation
