### ISSUE TITLE
Accessing intermediate layer analyzer output

### ISSUE THREAD

**Issue by acv132** [albermax/innvestigate#234]
I would like to access the intermediate output of an LRP analysis of a model created with keras. Is there a function to do so?

**Comment by adrhill** [comment]
Yes, analyzers of type `ReverseAnalyzerBase` take an optional parameter `reverse_keep_tensors=True`, which will store all intermediate tensors on the backward pass.

[Check out the docs](https://innvestigate.readthedocs.io/en/latest/modules/analyzer.html#innvestigate.analyzer.base.ReverseAnalyzerBase) for more details.
