### ISSUE TITLE
Cannot install innvestigate to use with Keras 2.4.3

### ISSUE THREAD

**Issue by roma-glushko** [albermax/innvestigate#236]
Trying to install innvestigate along with Keras 2.4.3, but innvestigate doesn't seem to support it:

<img width="980" alt="Screenshot 2021-01-21 at 22 11 26" src="https://user-images.githubusercontent.com/9402690/105406936-c438a200-5c35-11eb-83c1-da3fe0e44da2.png">

I'm using poetry as a package manager (if this makes any difference). Do you have the same issue?

**Comment by adrhill** [comment]
Hi Roman, 

as far as I'm aware, Keras 2.4 is just a wrapper around TensorFlow 2's `tf.keras`. Poetry can not resolve your dependencies as the current releases of iNNvestigate only support TF1. 
We're working on an update to bring investigate to TF2, so stay tuned!
