### ISSUE TITLE
Possible to analyze a model not trained by tensorflow?

### ISSUE THREAD

**Issue by chnpenny** [albermax/innvestigate#239]
Hey, 
I'm from the field of ecology. I want to analyze a DNN model trained in R. Is it possible to 'fake' the result as a keras.model object to use your package or import the result of this model directly to innvestigate?
Thank you so much!

**Comment by rachtibat** [comment]
You need a complete, working tensorflow 1 model. So you have to convert the R model to tensorflow 1 version. But I don't know, if this is possible. Pytorch models for instance can be converted to tensorflow.

Best
