### ISSUE TITLE
Looking forward to pytorch suport

### ISSUE THREAD

**Issue by cuge1995** [albermax/innvestigate#243]

**Comment by adrhill** [comment]
Hi Jinlai Zhang,

thanks for your feedback!
We're currently focusing on bringing iNNvestigate to TF2. PyTorch support is also on our wish list, but will have to wait until our TF2 port runs smoothly. 

For the time being, I recommend you to check out [Zennit](https://github.com/chr5tphr/zennit), which implements LRP in PyTorch.
