### ISSUE TITLE
deconvolutional layers

### ISSUE THREAD

**Issue by envytails** [albermax/innvestigate#244]
Is possible using Innvestigate on deconv. layers?

**Comment by adrhill** [comment]
Hi envytails, 

it should be possible to use iNNvestigate on models with [Conv2DTranspose](https://keras.io/api/layers/convolution_layers/convolution2d_transpose/) and [Conv3DTranspose](https://keras.io/api/layers/convolution_layers/convolution3d_transpose/) layers.
