### ISSUE TITLE
Implmentation of the gamma-rule

### ISSUE THREAD

**Issue by SevenFoldDeep** [albermax/innvestigate#249]
My issue is that it seems that the gamma rule is not implemented? This rule is often mentioned in papers and is also recommended as the optimal rule for certain neural net layers, but I have been unable to decipher which of the rules offered in this package can be used for the gamma rule. Thus I find it a bit hard to believe that this rule has not been included in this package. But if that is the case, are there any plans on implementing it in the near future?
If this rule has indeed been implemented in this package then please improve the documentation so that future users can find out which one it is.

**Comment by HugoTex98** [comment]
I have the same doubt @SevenFoldDeep!
Also, I would like to know if there is any way to implement LRP composite in the toolbox?

**Comment by SevenFoldDeep** [comment]
Yes I was also unsure of how to apply a composite of rules. I guess there is likely a way to accomplish this but it is not clear from the documentation or examples. I will likely look into figuring it out myself in the next week or so and let you know if I figure it out.

**Comment by HugoTex98** [comment]
Thanks @SevenFoldDeep I'll do the same, since I'm involved in a project that is using this toolbox.

**Comment by adrhill** [comment]
Hi @SevenFoldDeep ,

LRP-gamma is currently implemented in the [`updates_towards_tf2.0` branch](https://github.com/albermax/innvestigate/blob/updates_towards_tf2.0/innvestigate/analyzer/relevance_based/relevance_analyzer.py#L455-L477) of iNNvestigate. For the TF2.0 release, it will be merged into master.

For custom LRP composites, you can [create a `LRP` analyzer](https://github.com/albermax/innvestigate/blob/b1084b2b5c59434060c78bb163b9bf006f5bbeb8/innvestigate/analyzer/relevance_based/relevance_analyzer.py#L329)  using the kwargs `rule`, `input_layer_rule`, `until_layer_rule` and `bn_layer_rule`. You can find individual rules [here](https://github.com/albermax/innvestigate/blob/master/innvestigate/analyzer/relevance_based/relevance_rule.py).
It might be helpful to first read the [Introduction to development](https://github.com/albermax/innvestigate/blob/master/examples/notebooks/introduction_development.ipynb) to get a feeling for how iNNvestigate works under the hood.
