### ISSUE TITLE
When is tf.keras functionality coming? 

### ISSUE THREAD

**Issue by davidwdw** [albermax/innvestigate#251]
Thanks for providing this package! 

I'm trying to implement it in my research but all my models were built using tf.keras instead of keras. 

I know this has been answered a couple of weeks before, but I would just like to find out when the update on this is coming? 

Thanks!

**Comment by adrhill** [comment]
Hi @davidwdw,

Thank you for your interest! We'll move to `tf.keras` with our TF2 release. 
Currently we are aiming for a first release before August.
