### ISSUE TITLE
Error with Collect Layers for functional models for TF 2.1

### ISSUE THREAD

**Issue by adityajain93** [albermax/innvestigate#253]
def collect_layers(container):
        for layer in container.layers:
            # assert layer not in ret
            if layer not in ret:
                ret.append(layer)
            if kchecks.is_network(layer):
                collect_layers(layer)
    collect_layers(model)

If we have a functional keras model with shared layers. Something like an autoencoder 
in which the input is shared with the encoder model and the autoencoder, the 
assert statement fails when trying to explain the autoencoder.

Any ideas on how to get around it!

I'm trying to explain a neural net with LRP Epsilon in the updates_to_tf2.0 branch

**Comment by nboutry** [comment]
Hi,

Can someone please tell me how I can unsubscribe ?

Best,
N.B.

**Comment by adrhill** [comment]
Hi @adityajain93,

we just released [iNNvestigate 2.0](https://github.com/albermax/innvestigate/releases/tag/2.0.0) with support for TensorFlow 2! 
Please try it out and let me know if this fixes your issue. :)
