### ISSUE TITLE
[REQUEST] Working with newer Keras version

### ISSUE THREAD

**Issue by tregua87** [albermax/innvestigate#265]
Dear,

I am working with a Keras Version: 2.4.3. but the current iNNvestigate requires keras==2.2.4.

Are you planning to upgrade the library?

Alternatively, is it possible to install the iNNvestigate from the source code? So I can try to make a port myself.

I am just interested in the LRP explanation.

Thanks :)

**Comment by adrhill** [comment]
Hi Flavio, 

iNNvestigate currently requires Keras <= 2.3 as it uses TF1. 
A TF2 port is actively being developed. The plan is to switch to to the newest `tf.keras` bundled with TensorFlow.

You can install iNNvestigate from source using either `pip install` or using [Poetry](https://python-poetry.org) and `poetry install`.

**Comment by tregua87** [comment]
Thank you,

I saw you guys are working on a new iNNvestigate version for TF2. Do you have any tentative release date?

Meanwhile, I will play with the source code, thanks :)

**Comment by adrhill** [comment]
Soon, we're aiming for end of July / beginning of August. :)
