### ISSUE TITLE
'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by Yung-zi** [albermax/innvestigate#268]
### Read the docs
Before opening an issue, try to find a solution in the [iNNvestigate docs](https://innvestigate.readthedocs.io/en/latest/) and consider using the issue search function to look for similar issues. Thanks!
___

### Steps to reproduce the bug
Ideally include a minimal code example in Python that reproduces the bug:

```python
"Replace me with your code!"
```

### Platform information
 - OS: [e.g. Ubuntu 20.04, Windows 10]
 - Python version: [e.g. 3.7, 3.8, 3.9]
 - iNNvestigate version: [e.g. 1.0.9]
 - TensorFlow version: [e.g. 1.15]

**Comment by adrhill** [comment]
Hi @Yung-zi,

it's impossible to pinpoint your issue without context. 
If this error still occurs, please reopen this issue with a small code example.
