### ISSUE TITLE
[REQUEST] Need a little bit detailed explanation for some LRP methods...

### ISSUE THREAD

**Issue by yang0920colostate** [albermax/innvestigate#269]
Hi,

Could you kindly explain in detail what rules do each of the following methods uses? In the [documentation](https://innvestigate.readthedocs.io/en/latest/modules/analyzer.html#module-innvestigate.analyzer.relevance_based.relevance_analyzer), it only stated "Special LRP-configuration for ConvNets".

1) LRPSequentialPresetA
2) LRPSequentialPresetB
3) LRPSequentialPresetAFlat
4) LRPSequentialPresetBFlat

Thank you in advance!

**Comment by sebastian-lapuschkin** [comment]
first, thank you @martindyrba .

in short, *Preset* uses LRP-epsilon in dense layers and LRP-alpha-beta in conv layers, in general.
Detailed differences are: 
*PresetA* uses alpha=1, beta=0
*PresetB* uses alpha=2, beta=1

All presets concluding in *Flat applies the LRP-flat rule (ie uniform distribution or relevances only adhering to the model's connectivity structure, disregarding weights and activations) in the lowest convolutional layer.
