### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amirh1374** [albermax/innvestigate#281]
Hi everyone, I hope you are doing great.

Thanks for getting into migrating this awesome library to TF2. However, I am not able to get it working. It seems that *innvestigate.create_analyzer()* is not supposed to be used to create analyzer objects. Previously working snippets result in the **AttributeError: module 'innvestigate' has no attribute 'create_analyzer'**. I believe the reason behind it is that things have changed in the current version; therefore, I would appreciate the update of examples available as they seem invalid now.

Thank you very much for all the efforts you make.

Best regards
Amirhossein Berenji

**Comment by adrhill** [comment]
Hi @amirh1374, thanks for your kind words! 
Did you manage to fix your issue? `innvestigate.create_analyzer()` should be available.
