### ISSUE TITLE
I have rather basic issue, I am having trouble in importing 'import utils.imagenet as imagenetutils' [BUG]

### ISSUE THREAD

**Issue by atifkhanncl** [albermax/innvestigate#290]
### Describe the bug
After installing innvestigate, I can import it but utils.imagenet i can't. Can you let me know if there are extra packages I have to install

```python
"import utils as eutils
import utils.imagenet as imagenetutils"
```

### Expected behavior
ModuleNotFoundError: No module named 'utils'

### Platform information
 - OS: [e.g. Ubuntu 22.04]
 - Python version: [e.g. 3.8]
 - iNNvestigate version: [e.g. 2.0.0]
 - TensorFlow version: [e.g. 2.9.1]

**Comment by adrhill** [comment]
Hi @atifkhanncl,

I'm guessing you tried running the notebooks in the example folder. `import utils.imagenet` imports the [module in `/examples/utils`](https://github.com/albermax/innvestigate/tree/master/examples/utils), which is not part of iNNvestigate itself.

You have to copy/clone the entire `/examples/utils` folder to run the notebooks locally.
