### ISSUE TITLE
Cannot install innvestigate 2.0.1 on macOS with tensorflow-macos

### ISSUE THREAD

**Issue by miriamelia** [albermax/innvestigate#291]
### Describe the bug
Can not install innvestigate version 2.0.1 via pip on mac-os with arm64.
(When installing an earlier version I run into a version mismatch since I need keras 2.8 and innvestigate 1.9 uses keras 2.2.4)

### Steps to reproduce the bug
 ```
pip install innvestigate==2.0.1 
                            
Collecting innvestigate==2.0.1
  Using cached innvestigate-2.0.1-py3-none-any.whl (66 kB)
Requirement already satisfied: matplotlib<4.0.0,>=3.5.1 in /Users/.../lib/python3.8/site-packages (from innvestigate==2.0.1) (3.5.1)
Collecting numpy<2.0,>=1.22
  Using cached numpy-1.23.3-cp38-cp38-macosx_11_0_arm64.whl (13.3 MB)

ERROR: Could not find a version that satisfies the requirement tensorflow<2.11,>=2.6 (from innvestigate) (from versions: none)
ERROR: No matching distribution found for tensorflow<2.11,>=2.6
```

But I have tensorflow for mac os with arm64 installed:

```
>>> import tensorflow as tf
>>> print(tf.__version__)
2.8.0
```

conda list:
`tensorflow-macos          2.8.0                    pypi_0    pypi`

### Expected behavior

I believe this problem could be solved if you added 'tensorflow-macos  (2.8.0) ' to the requirements.txt file

### Platform information
 - OS: [macOS Monterey]
 - Python version: [3.8.13]
 - iNNvestigate version: [2.0.1]
 - TensorFlow version: [tensorflow-macos  2.8.0]

**Comment by adrhill** [comment]
Hi @miriamelia,

I'm also on macOS Monterey (12.6) and successfully installed iNNvestigate in a fresh virtual environment using 
```
pip install innvestigate==2.0.1 tensorflow
```

To me, the error `ERROR: No matching distribution found for tensorflow<2.11,>=2.6` looks suspicious, since it sounds like your installation of pip can't find any distribution of TensorFlow.

Could you try to update pip via `pip install --upgrade pip` and run the install command above? Maybe this already fixes your issue.

**Comment by miriamelia** [comment]
Hi @adrhill, 

thank you for your quick response.
I created a new conda env with pip version:
`pip                       22.2.2             pyhd8ed1ab_0    conda-forge`

same error when running your command above:
`pip install innvestigate==2.0.1 tensorflow
Collecting innvestigate==2.0.1
  Using cached innvestigate-2.0.1-py3-none-any.whl (66 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow`

However, when I installed it via `pip install -e <path_to_local_directory>` after adjusting pyproject.toml and requirements.txt to include tensorflow-macos verison 2.8.0, I could install innvestigate

Does your mac use arm64 or x86?

**Comment by adrhill** [comment]
## `pyproject.toml`
The `pyproject.toml` should in theory not be overly restrictive on the used version of TF. Currently it allows anything over `2.5` and doesn't set any bounds for packages such as `tensorflow-macos`. This is all iNNvestigate asks for:
https://github.com/albermax/innvestigate/blob/0d5f69968fc2a613f4eb73b53c42d124ffbb0dcc/pyproject.toml#L34-L39

I try to avoid conda, so I can't tell you why it fails to find a TensorFlow distribution for arm64 (I am indeed on x86). 
Is the problem that iNNvestigate strictly requires `tensorflow` but M1/M2 Macs have to use `tensorflow-macos` instead?

Which changes did you have to make to the `pyproject.toml`? 

## `requirements.txt`
I will rename the `requirements.txt` to something like `dev_env_requirements.txt`. It was not meant to be used to install iNNvestigate as it is just an auto-generated mirror of my dev environment for the purpose of full reproducibility (setting strict minor version requirements for each dependency).

**Comment by miriamelia** [comment]
Alright, I simply added tensorflow-macos = ">=2.6.0":

<img width="268" alt="image" src="https://user-images.githubusercontent.com/29278598/195689572-c9b443ea-2142-427b-bc21-143ea089f1bc.png">

**Comment by adrhill** [comment]
This will have to stay a manual fix for Conda + ARM Mac users since I can't add `tensorflow-macos` as a dependency for everyone.

Maybe it's worth opening an issue in either the Conda or TensorFlow repository. The desired behaviour should be to simply install `tensorflow` regardless of the platform it is run on.
