### ISSUE TITLE
[BUG] Remove `analyzer.fit()` from all example files. All example files using `analyzer.fit` method are broken

### ISSUE THREAD

**Issue by Rstar1998** [albermax/innvestigate#298]
Remove `analyzer.fit()` from all example files. All example files using `analyzer.fit` method are broken

I was running example file  `examples/mnist_compare_methods.ipynb` and I got error that `analyzer.fit` method doesn't exists and it was removed in this release [https://github.com/albermax/innvestigate/releases/tag/2.0.1]

**Comment by adrhill** [comment]
Hi @Rstar1998, thanks for the issue! This should be fixed now. :)
