### ISSUE TITLE
DeconvNet: Possible  Bug

### ISSUE THREAD

**Issue by sebastian-lapuschkin** [albermax/innvestigate#67]
The results for DeconvNet deviate in between

[the pikinder/nn-patterns notebook](https://github.com/pikinder/nn-patterns/blob/master/examples/all_methods.ipynb)
and [our notebooks](https://github.com/albermax/innvestigate/blob/feature/notebook/examples/notebooks/imagenet_example.ipynb)

I suggest, judging by the way ours looks, that this is not only a visualization issue but something more grave.

@albermax , can you compare both code bases?

**Comment by albermax** [comment]
No, they are not in the official repo. One of the reasons is that the LRN-layer is not supported anymore. Which means we would need to support that layer and also have an implementation for LRP.

Let's keep in mind and discuss it once the release is done!
