### ISSUE TITLE
Future module import issue

### ISSUE THREAD

**Issue by milongo** [albermax/innvestigate#76]
Hi,

Trying to run `innvestigate/examples/notebooks/mnist_example.ipynb` it complains about a 
 ` from future.utils import raise_with_traceback, raise_from
      6 # catch exception with: except Exception as e` 
` ImportError: No module named 'future'`.

I tried running `python setup.py test` and it builds a couple folders but none named `future`. Tried commenting the import but a bunch of different files try to do this import as well. 

Any help would be appreciated.

**Comment by sebastian-lapuschkin** [comment]
Hi milongo, 

can you ensure your python command executes python3.5(+) ?
Support for python2 is not 100% done in the current state.

Cheers,

**Comment by milongo** [comment]
Yes, I made sure to create an Anaconda version with Python 3.5.

**Comment by albermax** [comment]
I just saw that "six" is not part of the module list. Maybe this causes this behavior. Do you have the python module "six" installed too?

**Comment by milongo** [comment]
@cod3licious and @albermax how do I install these packages? The readme doesn't specify how to run the command. I did `python setup.py test` but the error persists.

**Comment by cod3licious** [comment]
did you try executing `pip install git+https://github.com/albermax/innvestigate` (from the installation instructions in the readme)?

**Comment by milongo** [comment]
@cod3licious Oh I did skip running that line... It's working now. Thanks for helping me with this! I'll be checking out the examples and library now. Looks great!
