### ISSUE TITLE
What is the difference between LRP and LRP_presetA and B?

### ISSUE THREAD

**Issue by wjNam** [albermax/innvestigate#92]
Hi i'm studying the method for interpreting deep networks and have some questions about the method implemented in here.

I don't know the meaning of LRP_presetA and LRP_presetB.
are A and B meaning alpha and beta parameter?

I read the paper which introduce the LRP-z and LRP-w. Also i know that alpha beta lrp shows the positive and negative relevance of the decision.

And all methods implemented here are pioneering and excellent. But is there a way to get the best of them?

Thank you for reading.

**Comment by sebastian-lapuschkin** [comment]
Hi wjNam,

---

# The LRP presets

LRP  (without any further additions) is equivalent to epsilon-LRP (with a small epsilon) for all layers of the network

In contrast to that, the LRP_preset methods have been found to be the empirically best configurations for sequential models with relu-like activation fxns and are consequently used in all our recent publications (2017+).

The gist of those preset configurations are:
- use epsilon-LRP for dense layers (mostly located in the end, the "decision makers" of the model)
- use alpha,beta-LRP for conv-layers (mostly located in the beginnig, the "feature extractors" of the model)

The presets are known to better reflect the decisions of the classifier than "just" LRP for sufficiently deep networks.
The difference between A and B is:
A = alpha=1,beta=0
B = alpha=2,beta=-1

Note that there also are LRPSequentialPresetAFlat and LRPSequentialPresetBFlat preconfigurations, which apply the "flat rule" (which applies uniform weights to all neural network connections in the relevance backward pass) in the lowest layer(s).
This introduces an invariance to the normalization of the input and effectively allows to visualize the relevance of higher layer neurons. Might be interesting in cases where networks of different structure are to be compared at the same scale (e.g. neuron receptive field wrt input pixels).

---

# Picking the "best" method
For choosing any method as the "best" it is important to know what kind of information the computed saliency maps should convey.
- Sensitivity Analysis for example informs about sensitive pixels, ie *where* change can potentially maximimally change the f(x).
- Deconvolution maps show which pixels in input space maximally activate an analyzed network output
- LRP shows which parts of the input cause a classifier to decide for or against the analyzed class (by how much)
- etc

I can not stress enough, that for picking **THE BEST METHOD**, considering the context of its analysis is important.

A possible approach would be to use some kind of input perturbation method  (implemented in this toolbox,  yet not fully verified (!)).
For refenrence, have a look at this paper:

```
@ARTICLE{SamTNNLS17,
  author = {Wojciech Samek and Alexander Binder and Gr{\'e}goire Montavon and Sebastian Lapuschkin and Klaus-Robert M{\"u}ller},
  title = {Evaluating the visualization of what a Deep Neural Network has learned},
  journal = {IEEE Transactions on Neural Networks and Learning Systems},
  year = {2017},
  volume = {28},
  number = {11},
  pages = {2660-2673},
  doi = {10.1109/TNNLS.2016.259982},
  url = {http://dx.doi.org/10.1109/TNNLS.2016.259982}
}
```

**Comment by wjNam** [comment]
Hi
Can i know the references of the paper which applied LRP_presetA and LRP_presetB method?

Thank you

**Comment by sebastian-lapuschkin** [comment]
preset A (alpha=1,beta=0) implements DTD (without the stricter constraints brought with DTD): https://www.sciencedirect.com/science/article/pii/S0031320316303582?via%3Dihub

preset B ist used in https://ieeexplore.ieee.org/document/8265401/
