### ISSUE TITLE
How to treat first input layer differently

### ISSUE THREAD

**Issue by enryH** [albermax/innvestigate#93]
Hey,
I try to decompose a fairly simply FNN, like your toy example of MNIST. I wonder if it is currently possible to select decomposition methods layer-wise, especially using the z-beta-rule on inputs to rescale the relevances as proposed in 

> Montavon, G., Lapuschkin, S., Binder, A., Samek, W., & Müller, K.-R. (2017). Explaining nonlinear classification decisions with deep Taylor decomposition. Pattern Recognition, 65, 211–222. https://doi.org/10.1016/J.PATCOG.2016.11.008

Cheers,
Henry

**Comment by albermax** [comment]
Hi Henry,

yes, you can use the "deep_taylor.bounded" analyzer which uses the bounding rule in the first layer (and therefore you need to pass the min/max values to the analyzer). Please note that currently the analyzer does not check if the final output of the FNN is positive (as required by Deep-Taylor), thus to be theoretically correct you need to check that yourself for now.

Does this solve your problem?

Cheers,
Max

**Comment by enryH** [comment]
Thanks Max. This was indeed the question and I have not noticed this method before.

Concerning the positivity constraint: Yes, I have seen the assumption in the paper that f(x)> 0. If you use a FNN for classifications, the output-activation always full-fills this property. However, and this is less clear to me, you guys seem to take the linear combination of weights and last layer hidden units activations to decompose relevances. Is this a heuristic or is it strictly necessary?

Cheers, Henry

**Comment by albermax** [comment]
Hi Henry,

yes, that would be a way to enforce it!

I'm not sure if I understand you point. Would you please elaborate it or point me to a line of code/formula?
Thanks!

Cheers,
Max

**Comment by enryH** [comment]
Hey Max,

i refer to e.g. in a binary case, the sigmoid activation layer on the output, this is f(z) = e^z / (e^z + 1), which is always positive. (The same holds for softmax in mutliclass problems).

On www.heatmapping.org (in the [Tutorial](http://heatmapping.org/tutorial/) and the[Conference talks](http://interpretable-ml.org/cvpr2018tutorial/)), they always set the initial relevance to decompose to x, which is the linear combination of neuron activation in the last hidden layer, h_last, and weights connecting last hidden layer to the output layer, w_last, i.e. z = w_last^\prime * h_last.

I just noticed that you came to add DTD and bounded DTD - lucky me:) Just to be sure, these are the correct function calls: 

`analyer  = innvestigate.create_analyzer("deep_taylor", model)
analyer  = innvestigate.create_analyzer("deep_taylor.bounded", model, low= 0, high= 1)`

Thanks for the help so far,
Henry

**Comment by albermax** [comment]
Maybe there is a misunderstanding. The bounded rule is meant for bounded input, not for bounded output. Does this help you?

The function calls are right, but the second analyzer assumes that the input regime is between 0 and 1.

Cheers,
Max

**Comment by albermax** [comment]
Thanks you for the reminder! It runs, but it's not theoretically justified and I will block it.
