### ISSUE TITLE
DeepTaylorSupport

### ISSUE THREAD

**Issue by albermax** [albermax/innvestigate#96]
Todos to finish deep taylor support:

* [x] Ensure positive output: put ReLU on top of the last neuron.
* [x] Using LRP-A1B0 with biases.
* [x] Zb rule as input rule.
* [x] Replace max-pooling with avg-pooling on the backward pass.
* [x] Review handling of batch-norm layer.

**Comment by enryH** [comment]
Isn't it LRP-A1B0 withOUT biases?

**Comment by albermax** [comment]
No, that class is called LRPAlpha1Beta0IgnoreBias.

See line 715-732 and the DeepTaylor definition in line 846 here:
https://github.com/albermax/innvestigate/blob/master/innvestigate/analyzer/relevance_based/relevance_analyzer.py
